### ISSUE TITLE
Error on groupEventsByDate(events, today = new Date())

### ISSUE THREAD

**Issue by ndac-todoroki** [bmathews/menubar-calendar#26]
I git cloned it to my ubuntu unity laptop, and done `npm start` but only the icon came out.
So I did `npm test` to get the result shown below:

```
> menu-calendar@1.0.0 test /home/me/git/menubar-calendar
> npm run lint  && npm run tape


> menu-calendar@1.0.0 lint /home/me/git/menubar-calendar
> eslint client server tests


/home/me/git/menubar-calendar/server/api/CalendarAPI.js
  58:5  warning  Unexpected console statement  no-console
  65:5  warning  Unexpected console statement  no-console
  76:5  warning  Unexpected console statement  no-console
  80:7  warning  Unexpected console statement  no-console
  87:7  warning  Unexpected console statement  no-console

/home/me/git/menubar-calendar/server/CalendarStore.js
  23:5  warning  Unexpected console statement  no-console
  34:5  warning  Unexpected console statement  no-console

/home/me/git/menubar-calendar/server/oauth/ElectronGoogleAuth.js
  28:5  warning  Unexpected console statement  no-console

/home/me/git/menubar-calendar/server/server.js
  70:5  warning  Unexpected console statement  no-console

/home/me/git/menubar-calendar/server/SyncService.js
  34:5  warning  Unexpected console statement  no-console
  38:5  warning  Unexpected console statement  no-console
  45:7  warning  Unexpected console statement  no-console
  49:7  warning  Unexpected console statement  no-console
  53:7  warning  Unexpected console statement  no-console
  62:5  warning  Unexpected console statement  no-console

> menu-calendar@1.0.0 tape /home/me/git/menubar-calendar
> tape -r babel-register tests/**/*.js | faucet

/home/me/git/menubar-calendar/client/utils/eventUtils.js:83
  groupEventsByDate(events, today = new Date()) {
                                  ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at loader (/home/me/git/menubar-calendar/node_modules/babel-register/lib/node.js:148:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/me/git/menubar-calendar/node_modules/babel-register/lib/node.js:158:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (eventUtils.js:2:1)
    at Module._compile (module.js:410:26)
not ok 1 no plan found
not ok 2 no assertions found
⨯ fail  2

npm ERR! Linux 4.4.0-32-lowlatency
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "tape"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! menu-calendar@1.0.0 tape: `tape -r babel-register tests/**/*.js | faucet`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the menu-calendar@1.0.0 tape script 'tape -r babel-register tests/**/*.js | faucet'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the menu-calendar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tape -r babel-register tests/**/*.js | faucet
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs menu-calendar
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls menu-calendar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/me/git/menubar-calendar/npm-debug.log
npm ERR! Test failed.  See above for more details.
```

maybe this is preventing the app to work?

**Comment by bmathews** [comment]
Try updating your version of node to 6+ and re-installing all the node modules.

**Comment by ndac-todoroki** [comment]
okay sorry for that... I only had the LTS version of node and now I upgraded to v6... and here's what I now get

```
> menu-calendar@1.0.0 tape /home/me/git/menubar-calendar
> tape -r babel-register tests/**/*.js | faucet

⨯ getEventsForDay
  not ok 5 should be equivalent
    ---
      operator: deepEqual
      expected: |-
        [ { end: { dateTime: '2016-06-06T20:00:00Z' }, start: { dateTime: '2016-06-06T20:00:00Z' } } ]
      actual: |-
        []
    ...
✓ getDatesForEvent
✓ getEventStartDate
✓ getEventEndDate
⨯ groupEventsByDate
  not ok 11 should be equivalent
    ---
      operator: deepEqual
      expected: |-
        { 'Monday 6/6/16': [ { end: { date: '2016-06-08' }, start: { date: '2016-06-06' } } ], 'Sunday 6/5/16': [ { end: { date: '2016-06-08' }, start: { date: '2016-06-06' } } ] }
      actual: |-
        { 'Monday 6/6/16': [ { end: { date: '2016-06-08' }, start: { date: '2016-06-06' } } ], 'Today 6/7/16': [ { end: { date: '2016-06-08' }, start: { date: '2016-06-06' } } ] }
    ...
✓ isBetween
✓ same day range
✓ two day range
✓ three day range
# tests 22
# pass  20
⨯ fail  2

npm ERR! Linux 4.4.0-32-lowlatency
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "tape"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! menu-calendar@1.0.0 tape: `tape -r babel-register tests/**/*.js | faucet`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the menu-calendar@1.0.0 tape script 'tape -r babel-register tests/**/*.js | faucet'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a ......
```

and still no window comes out after the oauth window in `npm start`
![_shutter_20160729_0002](https://cloud.githubusercontent.com/assets/11530165/17237633/080335d4-558f-11e6-95ab-b241b51d1e4c.png)

**Comment by bmathews** [comment]
Ugh, dealing with timezones is hard 😧 ! Those date issues wouldn't stop the app from working though.

If you run `npm run dev` instead, you should get a developer console. If there're errors there, could you post them? 

I'd like to track this down myself, but I probably won't be able to find time to get an Ubuntu VM up and running any time soon.
