### ISSUE TITLE
Can't when using electron-packager - /events.db no such file or directory

### ISSUE THREAD

**Issue by nicolaschaillot** [bmathews/menubar-calendar#28]
When packaging the app with electron-packager and try to launch the app, I have an error
```
Uncaught Exception:
OpenError: /events.db: No such file or directory
    at /Users/nicolasc/Documents/dev/apps/keendoo-events/release-builds/Last events app-darwin-x64/Last events app.app/Contents/Resources/app.asar/node_modules/levelup/lib/levelup.js:119:34
    at /Users/nicolasc/Documents/dev/apps/keendoo-events/release-builds/Last events app-darwin-x64/Last events app.app/Contents/Resources/app.asar/node_modules/medeadown/medeadown.js:28:14
    at /Users/nicolasc/Documents/dev/apps/keendoo-events/release-builds/Last events app-darwin-x64/Last events app.app/Contents/Resources/app.asar/node_modules/leveldown-open/leveldown-open.js:15:18
    at FSReqWrap.cb [as oncomplete] (fs.js:257:19)
```

npm script :
```
"package-mac": "electron-packager . --overwrite --asar=true --platform=darwin --arch=x64 --icon=src/client/assets/icons/mac/icon.icns --prune=true --out=release-builds",
```

<img width="437" alt="capture d ecran 2017-01-01 a 01 38 31" src="https://cloud.githubusercontent.com/assets/14954582/21579795/0844e9ee-cfc3-11e6-944f-932dcbeba997.png">

**Comment by nicolaschaillot** [comment]
Seams to be OK when using a custom path for LinvoDB (instead of process.cwd())
```
import Q from 'q';
import LinvoDB from 'linvodb3';
import medeadown from 'medeadown';

LinvoDB.defaults.store = { db: medeadown };
// LinvoDB.dbPath = process.cwd();
LinvoDB.dbPath = './tmp';

const Events = new LinvoDB('events', {});
```

**Comment by bmathews** [comment]
Related issue: https://github.com/electron/electron/issues/2108
